# Generated by Django 5.0.6 on 2025-09-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='banco_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='iban',
            field=models.CharField(blank=True, help_text='Ex: AO06004400012345678910152', max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='numero_conta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='swift',
            field=models.CharField(blank=True, help_text='Ex: BCOMAOXXXX', max_length=11, null=True, verbose_name='SWIFT/BIC'),
        ),
    ]
