# Generated by Django 4.2.10 on 2025-10-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaofiscal',
            name='regime_tributario',
            field=models.CharField(choices=[('geral', 'Regime Geral'), ('simplificado', 'Regime Simplificado (IVA)'), ('exclusao', 'Regime de Não Sujeição (Exclusão)'), ('outros', 'Outros (Regimes especiais e outros)')], default='geral', max_length=20),
        ),
    ]
