# Generated by Django 5.0.6 on 2025-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_configuracaofiscal_banco_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='email',
            field=models.CharField(blank=True, help_text='Ex: empresa@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='site',
            field=models.CharField(blank=True, help_text='Ex: empresa.com', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='telefone',
            field=models.CharField(blank=True, help_text='Ex: contacto da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracaofiscal',
            name='nif',
            field=models.CharField(help_text='Número de Identificação Fiscal da empresa.', max_length=14, verbose_name='NIF'),
        ),
    ]
