# Generated by Django 5.0.6 on 2025-09-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_configuracaofiscal_email_configuracaofiscal_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_banco', models.CharField(max_length=150, verbose_name='Nome do Banco')),
                ('numero_conta', models.CharField(max_length=50, verbose_name='Número da Conta')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, null=True, verbose_name='SWIFT/BIC')),
                ('configuracao_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='configuracoes.configuracaofiscal')),
            ],
            options={
                'verbose_name': 'Dado Bancário',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
    ]
