# Generated by Django 5.0.6 on 2025-09-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_dadosbancarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaofiscal',
            name='banco_nome',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscal',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscal',
            name='numero_conta',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscal',
            name='swift',
        ),
    ]
