# Generated by Django 5.0.6 on 2025-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorcamento',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='itemvenda',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='valor_total',
            new_name='total',
        ),
    ]
