# Generated by Django 5.1.5 on 2025-10-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='taxa_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
