# Generated by Django 5.0.6 on 2025-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_valor_total_itemorcamento_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentovenda',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='valor_taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
