# Generated by Django 5.1.5 on 2025-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_taxa_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='numero_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='numero_documento',
            field=models.CharField(default='FR NEWA1/001/2025', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
