# Generated by Django 5.1.5 on 2025-10-29 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_alter_documentofiscal_tipo_documento_saftexport'),
        ('vendas', '0002_itemvenda_taxa_iva_alter_pagamentovenda_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='taxa_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Regime Fiscal (AGT)'),
        ),
    ]
