# Generated by Django 5.1.5 on 2025-11-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_initial'),
        ('vendas', '0003_remove_venda_numero_venda_venda_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfatura',
            name='taxa_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Regime Fiscal (AGT)'),
        ),
        migrations.AddField(
            model_name='itemnotacredito',
            name='taxa_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Regime Fiscal (AGT)'),
        ),
        migrations.AddField(
            model_name='itemnotadebito',
            name='taxa_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Regime Fiscal (AGT)'),
        ),
        migrations.AddField(
            model_name='itemproforma',
            name='taxa_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Regime Fiscal (AGT)'),
        ),
    ]
