# Generated by Django 5.0.6 on 2025-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_pagamentovenda_valor_liquido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='iva_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do IVA'),
        ),
    ]
