# Generated by Django 5.0.6 on 2025-09-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_iva_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
