# Generated by Django 5.1.5 on 2025-11-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_itemfatura_taxa_iva_itemnotacredito_taxa_iva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturacredito',
            old_name='numero_fatura',
            new_name='numero_documento',
        ),
        migrations.RenameField(
            model_name='faturaproforma',
            old_name='numero_proforma',
            new_name='numero_documento',
        ),
    ]
