# Generated by Django 5.1.5 on 2025-11-14 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_rename_numero_fatura_faturacredito_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproforma',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
