# Generated by Django 5.0.6 on 2025-09-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produto_tem_iva_produto_iva_percentual'),
        ('vendas', '0006_itemvenda_iva_valor_itemvenda_nome_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='nome_produto',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='nome_comercial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.CharField(max_length=255),
        ),
    ]
