# Generated by Django 5.0.6 on 2025-09-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produto_tem_iva_produto_iva_percentual'),
        ('vendas', '0007_remove_itemvenda_nome_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='nome_comercial',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='nome_produto',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome do Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.produto'),
        ),
    ]
