# Generated by Django 5.0.6 on 2025-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_remove_itemvenda_nome_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
