# Generated by Django 5.0.6 on 2025-09-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_alter_venda_numero_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
