# Generated by Django 5.0.6 on 2025-09-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_venda_numero_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('balcao', 'Balcão'), ('entrega', 'Entrega'), ('online', 'Online')], default='balcao', max_length=200),
        ),
    ]
