# Generated by Django 5.0.6 on 2025-09-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('balcao', 'Balcão'), ('entrega', 'Entrega'), ('online', 'Online')], default='balcao', max_length=20),
        ),
    ]
