# Generated by Django 5.0.6 on 2025-09-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servico_desconto_percentual'),
        ('vendas', '0013_alter_venda_numero_venda_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='servicos.servico'),
        ),
    ]
