# Generated by Django 5.0.6 on 2025-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_itemvenda_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='duracao_servico_padrao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='instrucoes_servico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='nome_servico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Produto'),
        ),
    ]
