# Generated by Django 5.0.6 on 2025-09-28 01:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_foto'),
        ('core', '0004_contadordocumento'),
        ('produtos', '0012_alter_produto_foto'),
        ('servicos', '0007_servico_duracao_servico_padrao_and_more'),
        ('vendas', '0015_itemvenda_duracao_servico_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(max_length=200, unique=True, verbose_name='Número da Fatura (FT)')),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_faturado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Recebido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Pago Parcialmente'), ('liquidada', 'Liquidada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_credito', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Fatura Crédito',
                'verbose_name_plural': 'Faturas Crédito',
            },
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=255, verbose_name='Nome/Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('desconto_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto (Valor)')),
                ('iva_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% IVA')),
                ('iva_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal Bruto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total do Item (c/ IVA)')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.faturacredito', verbose_name='Fatura de Crédito')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Item da Fatura de Crédito',
                'verbose_name_plural': 'Itens da Fatura de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=200, unique=True, verbose_name='Número do Recibo (REC)')),
                ('data_recibo', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Recebido')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='core.empresa')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='vendas.faturacredito', verbose_name='Fatura a Liquidar')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento', verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
