# Generated by Django 5.0.6 on 2025-09-28 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_foto'),
        ('core', '0004_contadordocumento'),
        ('produtos', '0012_alter_produto_foto'),
        ('servicos', '0007_servico_duracao_servico_padrao_and_more'),
        ('vendas', '0016_faturacredito_itemfatura_recibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proforma', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número da Proforma')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(help_text='Prazo para o cliente aceitar o orçamento.', verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('emitida', 'Emitida (Pendente)'), ('aceite', 'Aceite'), ('rejeitada', 'Rejeitada'), ('convertida', 'Convertida em Vatura/Venda')], default='emitida', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto_global', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas_emitidas', to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas_proprias', to='core.empresa', verbose_name='Empresa Emitente')),
            ],
            options={
                'verbose_name': 'Fatura Proforma',
                'verbose_name_plural': 'Faturas Proforma',
                'ordering': ['-data_emissao', 'numero_proforma'],
                'permissions': [('aprovar_faturaproforma', 'Pode aprovar Faturas Proforma'), ('imprimir_faturaproforma', 'Pode imprimir Faturas Proforma')],
            },
        ),
        migrations.CreateModel(
            name='ItemProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.faturaproforma')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.servico')),
            ],
        ),
    ]
