# Generated by Django 5.0.6 on 2025-09-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_faturaproforma_itemproforma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faturacredito',
            options={'permissions': [('liquidar_faturacredito', 'Pode liquidar Faturas a Crédito')], 'verbose_name': 'Fatura Crédito', 'verbose_name_plural': 'Faturas Crédito'},
        ),
    ]
