# Generated by Django 5.0.6 on 2025-09-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_movimentacaofinanceira_recibo'),
        ('vendas', '0018_alter_faturacredito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria', verbose_name='Conta Bancária de Crédito'),
        ),
    ]
