# Generated by Django 5.0.6 on 2025-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0020_alter_formapagamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaproforma',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
