# Generated by Django 5.0.6 on 2025-10-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0021_faturaproforma_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturaproforma',
            name='ativo',
        ),
    ]
