# Generated by Django 5.0.6 on 2025-10-01 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0022_remove_faturaproforma_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturaproforma',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
    ]
