# Generated by Django 5.0.6 on 2025-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0023_alter_faturaproforma_data_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('fatura_recibo', 'Fatura Recibo'), ('balcao', 'Balcão'), ('entrega', 'Entrega'), ('online', 'Online')], default='fatura_recibo', max_length=20),
        ),
    ]
