# Generated by Django 5.0.6 on 2025-10-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_rename_valor_total_capacitacao_total_and_more'),
        ('vendas', '0024_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacredito',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_credito_emitidas', to='funcionarios.funcionario'),
        ),
    ]
