# Generated by Django 4.2.10 on 2025-10-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_validade_ofa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero_ocpca',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero_ofa',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(editable=False, help_text='Gerada automaticamente no formato FUNC-00001', max_length=20, unique=True),
        ),
    ]
