# Generated by Django 5.1.5 on 2025-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='selecionar_todos',
            field=models.BooleanField(default=False, verbose_name='Selecionar todas as permissões'),
        ),
    ]
