# Generated by Django 5.0.6 on 2025-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='pode_dispensar_controlados',
            new_name='pode_editar_produtos',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='pode_dispensar_medicamentos',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='pode_prescrever',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='requer_ofa',
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_pagar_salario',
            field=models.BooleanField(default=True),
        ),
    ]
