# Generated by Django 5.0.6 on 2025-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_rename_pode_dispensar_controlados_cargo_pode_editar_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, default='funcionarios/fotos/funcionario.png', null=True, upload_to='funcionarios/fotos/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica'), ('estagiario', 'Estagiário'), ('terceirizado', 'Terceirizado'), ('freelancer', 'Freelancer'), ('voluntario', 'Voluntário')], default='pf', max_length=15),
        ),
    ]
