# Generated by Django 5.1.5 on 2025-10-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_cargo_pode_acessar_configuracao_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
