# Generated by Django 5.0.6 on 2025-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacitacao',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='ferias',
            old_name='valor_total',
            new_name='total',
        ),
    ]
