# Generated by Django 5.1.5 on 2025-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_cargo_codigo_alter_cargo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(editable=False, help_text='Gerada automaticamente no formato FUNC-00001', max_length=20),
        ),
    ]
