# Generated by Django 5.0.6 on 2025-10-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_rename_valor_total_capacitacao_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pode_aprovar_proforma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_emitir_faturacredito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_emitir_proforma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_liquidar_faturacredito',
            field=models.BooleanField(default=False),
        ),
    ]
