# Generated by Django 5.0.6 on 2025-10-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contadordocumento'),
        ('funcionarios', '0005_cargo_pode_aprovar_proforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.empresa'),
            preserve_default=False,
        ),
    ]
