# Generated by Django 5.0.6 on 2025-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_cargo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pode_estornar_pagamento',
            field=models.BooleanField(default=False, verbose_name='Pode Estornar Pagamentos de Vendas'),
        ),
    ]
