# Generated by Django 5.0.6 on 2025-10-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_contadordocumento'),
        ('funcionarios', '0007_cargo_pode_estornar_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funcionario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargo',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões nativas do sistema aplicáveis a este cargo. Serão sincronizadas automaticamente com o grupo correspondente.', to='auth.permission', verbose_name='Permissões do sistema (Django)'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='categoria',
            field=models.CharField(choices=[('diretoria', 'Diretoria'), ('gerencia', 'Gerência'), ('coordenacao', 'Coordenação'), ('supervisao', 'Supervisão'), ('operacional', 'Operacional'), ('tecnico', 'Técnico'), ('administrativo', 'Administrativo'), ('vendas', 'Vendas'), ('direcao_tecnica', 'Direção Técnica'), ('estagiario', 'Estagiário'), ('terceirizado', 'Terceirizado'), ('rh', 'Recursos Humanos'), ('financeiro', 'Contabilidade'), ('outros', 'Outros')], default='operacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Se vazio, é um cargo global do sistema (modelo base).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='limite_desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel_hierarquico',
            field=models.IntegerField(default=1, help_text='1 = Nível mais alto na hierarquia'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pode_estornar_pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='vale_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='vale_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Se vazio, é um departamento global (modelo padrão do sistema).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.loja'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Responsável dentro da empresa. Global não possui responsável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsavel', to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(help_text='Matrícula do funcionário', max_length=20),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['empresa', 'ativo'], name='funcionario_empresa_00252f_idx'),
        ),
    ]
