# Generated by Django 5.0.6 on 2025-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('funcionarios', '0008_alter_funcionario_unique_together_cargo_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões aplicáveis a este cargo (vinculadas ao grupo automaticamente).', to='auth.permission', verbose_name='Permissões do Django'),
        ),
    ]
