# Generated by Django 5.0.6 on 2025-10-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.cargo'),
            preserve_default=False,
        ),
    ]
