# Generated by Django 5.0.6 on 2025-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pode_acessar_configuracoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_acessar_financeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_acessar_rh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_emitir_recibo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_fornecedores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_ver_documentos',
            field=models.BooleanField(default=False),
        ),
    ]
