# Generated by Django 5.0.6 on 2025-10-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_cargo_pode_acessar_configuracoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='pode_fornecedores',
            new_name='pode_acessar_documentos',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='pode_ver_documentos',
            new_name='pode_acessar_fornecedores',
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_ver_vendas',
            field=models.BooleanField(default=False),
        ),
    ]
