# Generated by Django 5.1.5 on 2025-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_validacao',
            field=models.CharField(blank=True, help_text='Código de validação fornecido pela AT para ATCUD', max_length=500, null=True),
        ),
    ]
