# Generated by Django 5.0.6 on 2025-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, default='core/fotos/empresa.png', null=True, upload_to='core/fotos/'),
        ),
        migrations.AddField(
            model_name='loja',
            name='foto',
            field=models.ImageField(blank=True, default='core/fotos/loja.png', null=True, upload_to='core/fotos/'),
        ),
    ]
