# Generated by Django 5.0.6 on 2025-09-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_foto_loja_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='core/fotos/usuario.png', null=True, upload_to='core/fotos/'),
        ),
    ]
