# Generated by Django 5.0.6 on 2025-09-28 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FR', 'Fatura Recibo'), ('FT', 'Fatura'), ('REC', 'Recibo'), ('PP', 'Fatura Proforma')], max_length=5, unique=True, verbose_name='Tipo de Documento')),
                ('ano', models.IntegerField(default=2025)),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Contador de Documento',
                'verbose_name_plural': 'Contadores de Documentos',
                'unique_together': {('empresa', 'tipo_documento', 'ano')},
            },
        ),
    ]
