# Generated by Django 5.1.5 on 2025-11-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(blank=True, help_text='Nome completo do cliente', max_length=255),
        ),
    ]
