# Generated by Django 5.0.6 on 2025-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='aceita_marketing',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_aceite_termo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ip_aceite_termo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='medico_responsavel',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_carteira',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='plano_saude',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='termo_aceito',
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='clientes/fotos/cliente.png', null=True, upload_to='clientes/fotos/'),
        ),
        migrations.DeleteModel(
            name='DependenteCliente',
        ),
    ]
