# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaofidelidade',
            name='venda_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='historicocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='historicocliente',
            name='usuario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicocliente',
            name='venda_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='grupocliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_clientes', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='enderecocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contatocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.categoriacliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pagamento_preferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.formapagamento'),
        ),
        migrations.AddField(
            model_name='cartaofidelidade',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartao_fidelidade', to='clientes.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='contatocliente',
            unique_together={('cliente', 'tipo_contato', 'valor_contato')},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo_cliente'], name='clientes_cl_codigo__da5f56_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['bi'], name='clientes_cl_bi_e607d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome_completo', 'empresa'], name='clientes_cl_nome_co_a004e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefone'], name='clientes_cl_telefon_08ef14_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo', 'bloqueado'], name='clientes_cl_ativo_2121ae_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['data_ultima_compra'], name='clientes_cl_data_ul_f43620_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('codigo_cliente', 'empresa')},
        ),
    ]
