# Generated by Django 4.2.10 on 2025-10-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocliente',
            name='tipo_interacao',
            field=models.CharField(choices=[('compra', 'Compra'), ('devolucao', 'Devolução'), ('reclamacao', 'Reclamação'), ('elogio', 'Elogio'), ('ligacao', 'Ligação'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita'), ('outros', 'Outros')], max_length=15),
        ),
    ]
