# Generated by Django 5.0.6 on 2025-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_aceita_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(editable=False, help_text='Código interno do cliente', max_length=20, unique=True),
        ),
    ]
