# Generated by Django 5.0.6 on 2025-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='clientes/fotos/clientes.png', null=True, upload_to='clientes/fotos/'),
        ),
    ]
