# Generated by Django 5.0.6 on 2025-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome comercial pelo qual os clientes vão reconhecer e chamar a empresa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_social',
            field=models.CharField(blank=True, help_text='Nome usado para tratamento social', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Se for empresa | nome oficial de uma empresa, ou seja, o nome jurídico do negócio', max_length=255),
        ),
    ]
