# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='movimento_original',
            field=models.ForeignKey(blank=True, help_text='Movimento original que está sendo estornado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financeiro.movimentocaixa'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo movimento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
