# Generated by Django 5.1.5 on 2025-11-11 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoimposto',
            name='responsavel_fiscal',
            field=models.ForeignKey(blank=True, help_text='Funcionário responsável pelos assuntos fiscais', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='conciliacaobancaria',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_pagar', to='financeiro.contapai'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_receber', to='financeiro.contapai'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
