# Generated by Django 5.0.6 on 2025-09-29 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_rename_valor_total_impostotributo_total_and_more'),
        ('vendas', '0018_alter_faturacredito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='recibo',
            field=models.ForeignKey(blank=True, help_text='Recibo de Pagamento (REC) que originou esta entrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financeiras_origem', to='vendas.recibo'),
        ),
    ]
