# Generated by Django 4.2.10 on 2025-10-23 00:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0003_cargo_pode_acessar_configuracao_fiscal_and_more'),
        ('financeiro', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoimposto',
            options={'verbose_name': 'Configuração de Impostos Angola', 'verbose_name_plural': 'Configurações de Impostos Angola'},
        ),
        migrations.AlterModelOptions(
            name='impostotributo',
            options={'ordering': ['-ano_referencia', '-mes_referencia', 'data_vencimento'], 'verbose_name': 'Imposto/Tributo Angola', 'verbose_name_plural': 'Impostos/Tributos Angola'},
        ),
        migrations.RemoveIndex(
            model_name='impostotributo',
            name='financeiro__tipo_im_789785_idx',
        ),
        migrations.RenameField(
            model_name='impostotributo',
            old_name='arquivo_comprovante',
            new_name='arquivo_comprovante_pagamento',
        ),
        migrations.RenameField(
            model_name='impostotributo',
            old_name='compensacoes',
            new_name='compensacoes_utilizadas',
        ),
        migrations.AlterUniqueTogether(
            name='impostotributo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='configuracaoimposto',
            name='aliquota_cofins',
        ),
        migrations.RemoveField(
            model_name='configuracaoimposto',
            name='aliquota_iss',
        ),
        migrations.RemoveField(
            model_name='configuracaoimposto',
            name='aliquota_pis',
        ),
        migrations.RemoveField(
            model_name='configuracaoimposto',
            name='anexo_simples',
        ),
        migrations.RemoveField(
            model_name='configuracaoimposto',
            name='cnae_principal',
        ),
        migrations.RemoveField(
            model_name='configuracaoimposto',
            name='regime_tributario',
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_iac_depositos',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Alíquota IAC - Depósitos (%) - Padrão: 10%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_iac_titulos',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Alíquota IAC - Títulos (%) - Padrão: 15%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_imposto_industrial_especial',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Alíquota do Imposto Industrial - Setores Especiais (%) - Padrão: 35%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_imposto_industrial_geral',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Alíquota do Imposto Industrial - Geral (%) - Padrão: 25%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_imposto_selo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Alíquota do Imposto de Selo (%) - Padrão: 0,2%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_imposto_veiculos',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Alíquota do Imposto sobre Veículos (%) - Padrão: 2%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_iva_cabinda',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Alíquota do IVA para Cabinda (%) - Padrão: 1%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_iva_geral',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Alíquota do IVA - Regime Geral (%) - Padrão: 7%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aliquota_iva_simplificado',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Alíquota do IVA - Regime Simplificado (%) - Padrão: 5%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='aplicar_retencao_fonte',
            field=models.BooleanField(default=False, help_text='Empresa sujeita à retenção na fonte'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='centro_custo_impostos',
            field=models.ForeignKey(blank=True, help_text='Centro de custo padrão para impostos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='conta_impostos_diversos',
            field=models.ForeignKey(blank=True, help_text='Conta contábil para impostos diversos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracao_impostos_diversos', to='financeiro.planocontas'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='conta_iva_a_pagar',
            field=models.ForeignKey(blank=True, help_text='Conta contábil para IVA a pagar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracao_iva_pagar', to='financeiro.planocontas'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='data_ultima_atualizacao_aliquotas',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização das alíquotas'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='dias_antecedencia_notificacao',
            field=models.IntegerField(default=7, help_text='Dias de antecedência para notificação de vencimentos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='eh_setor_diamantifero',
            field=models.BooleanField(default=False, help_text='Empresa pertence ao setor diamantífero'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='eh_setor_mineiro',
            field=models.BooleanField(default=False, help_text='Empresa pertence ao setor mineiro'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='eh_setor_petrolifero',
            field=models.BooleanField(default=False, help_text='Empresa pertence ao setor petrolífero'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='impostos_aplicaveis',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos AGT dos impostos aplicáveis à empresa'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='notificar_vencimentos',
            field=models.BooleanField(default=True, help_text='Notificar sobre vencimentos de impostos'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='percentual_juros_mora_mensal',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Percentual de juros de mora mensal (%) - Padrão: 1,5%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='percentual_multa_atraso',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentual de multa por atraso (%) - Padrão: 10%', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='percentual_retencao_ii',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.50'), help_text='Percentual de retenção do Imposto Industrial (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='percentual_retencao_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.50'), help_text='Percentual de retenção do IVA (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='provincia',
            field=models.CharField(choices=[('luanda', 'Luanda'), ('benguela', 'Benguela'), ('huila', 'Huíla'), ('cabinda', 'Cabinda'), ('huambo', 'Huambo'), ('cunene', 'Cunene'), ('namibe', 'Namibe'), ('cuando_cubango', 'Cuando Cubango'), ('lunda_norte', 'Lunda Norte'), ('lunda_sul', 'Lunda Sul'), ('malanje', 'Malanje'), ('moxico', 'Moxico'), ('bie', 'Bié'), ('kuanza_norte', 'Kwanza Norte'), ('kuanza_sul', 'Kwanza Sul'), ('uige', 'Uíge'), ('zaire', 'Zaire'), ('bengo', 'Bengo')], default='luanda', help_text='Província onde a empresa está localizada', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='regime_iva',
            field=models.CharField(choices=[('iva_geral', 'Regime do IVA - Geral'), ('iva_simplificado', 'Regime do IVA - Simplificado'), ('iva_transitorio', 'Regime Transitório do IVA'), ('excluido_iva', 'Regime de Exclusão do IVA')], default='iva_geral', help_text='Regime específico do IVA', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='regime_tributario_principal',
            field=models.CharField(choices=[('geral', 'Regime Geral'), ('simplificado', 'Regime Simplificado'), ('iva_geral', 'Regime do IVA - Geral'), ('iva_simplificado', 'Regime do IVA - Simplificado'), ('iva_transitorio', 'Regime Transitório do IVA'), ('excluido_iva', 'Regime de Exclusão do IVA'), ('especial_petrolifero_mineiro', 'Regime Especial do Sector Petrolífero e Mineiro'), ('retencao_fonte', 'Regime de Retenção na Fonte'), ('isencao', 'Regime de Isenção')], default='geral', help_text='Regime tributário principal da empresa', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='responsavel_fiscal',
            field=models.ForeignKey(blank=True, help_text='Funcionário responsável pelos assuntos fiscais', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='configuracaoimposto',
            name='setor_atividade',
            field=models.CharField(choices=[('comercio', 'Comércio'), ('industria', 'Indústria'), ('servicos', 'Serviços'), ('construcao', 'Construção Civil'), ('bancario', 'Sector Bancário'), ('seguros', 'Sector de Seguros'), ('telecomunicacoes', 'Telecomunicações'), ('petroleo', 'Sector Petrolífero'), ('mineiro', 'Sector Mineiro'), ('transporte', 'Transporte'), ('turismo', 'Turismo e Hotelaria'), ('agricultura', 'Agricultura'), ('outros', 'Outros')], default='comercio', help_text='Setor principal de atividade da empresa', max_length=50),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='arquivo_declaracao_agt',
            field=models.FileField(blank=True, help_text='Arquivo da declaração enviada à AGT', null=True, upload_to='impostos/declaracoes/'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='arquivo_guia_pagamento',
            field=models.FileField(blank=True, help_text='Arquivo da guia de pagamento AGT', null=True, upload_to='impostos/guias/'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='codigo_imposto_interno',
            field=models.CharField(default=1, help_text='Código interno do sistema', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='codigo_receita_agt',
            field=models.CharField(choices=[('01I', '01I - IVA - Regime Geral'), ('02I', '02I - IVA - Importação'), ('03I', '03I - IVA - Regime Geral'), ('04I', '04I - IVA - Regime Simplificado'), ('05I', '05I - IVA - Regime Transitório'), ('06I', '06I - IVA - Outros'), ('01A', '01A - IAC - Títulos do Banco Central'), ('02A', '02A - IAC - Bilhetes e Obrigações do Tesouro'), ('03A', '03A - IAC - Depósito à Ordem'), ('04A', '04A - IAC - Depósito a Prazo'), ('05A', '05A - IAC - Dividendos/Lucros'), ('06A', '06A - IAC - Juros de Suprimentos'), ('07A', '07A - IAC - Mais Valias'), ('08A', '08A - IAC - Operações do Mercado Monetário'), ('09A', '09A - IAC - Royalties'), ('10A', '10A - IAC - Outros'), ('01B', '01B - IRT - Grupo A - Conta de Outrem'), ('02B', '02B - IRT - Grupo B - Conta Própria'), ('03B', '03B - IRT - Grupo C - Atividades Comerciais e Industriais'), ('01C', '01C - II - Regime Geral'), ('02C', '02C - II - Regime Simplificado'), ('03C', '03C - II - Retenção na Fonte - Residentes'), ('04C', '04C - II - Retenção na Fonte - Não Residentes'), ('05C', '05C - II - Diamantes'), ('06C', '06C - II - Ouro'), ('07C', '07C - II - Outros Minerais'), ('01D', '01D - IEJ - Casino'), ('02D', '02D - IEJ - Totobola'), ('03D', '03D - IEJ - Totoloto'), ('04D', '04D - IEJ - Angomilhões'), ('05D', '05D - IEJ - Outros Tipos de Jogos Sociais'), ('06D', '06D - IEJ - Apostas Hípicas'), ('07D', '07D - IEJ - Rifas e Concursos'), ('08D', '08D - IEJ - Combinações Aleatórias'), ('09D', '09D - IEJ - Lotarias'), ('10D', '10D - IEJ - Outros Jogos Presenciais'), ('11D', '11D - IEJ - Prémios - Casino'), ('12D', '12D - IEJ - Online - Receita Bruta'), ('13D', '13D - IEJ - Online - Prémios'), ('14D', '14D - IEJ - Prémios - Totobola'), ('15D', '15D - IEJ - Prémios - Totoloto'), ('16D', '16D - IEJ - Prémios - Angomilhões'), ('17D', '17D - IEJ - Prémios Online'), ('18D', '18D - IEJ - Prémios - Apostas Hípicas'), ('19D', '19D - IEJ - Prémios - Apostas Hípicas'), ('20D', '20D - IEJ - Prémios - Lotarias'), ('01E', '01E - IP - Rendimentos do Petróleo'), ('02E', '02E - ITP - Transações de Petróleo'), ('01F', '01F - IP - Predial sobre a Detenção'), ('02F', '02F - IP - Predial sobre Transmissões Onerosas'), ('03F', '03F - IP - Predial sobre Transmissões Gratuitas'), ('04F', '04F - IP - Predial sobre a Renda'), ('01G', '01G - IBM - Veículos Automotores - Ligeiros'), ('02G', '02G - IBM - Veículos Automotores - Pesados'), ('03G', '03G - IBM - Motociclos, Ciclomotores, Triciclos e Quadriciclos'), ('04G', '04G - IBM - Veículos Automotores - Aeronaves'), ('05G', '05G - IBM - Veículos Automotores - Embarcações'), ('06G', '06G - IBM - Sucessões'), ('07G', '07G - IBM - Doações'), ('01H', '01H - IPD - Produção de Petróleo'), ('02H', '02H - IPD - Produção de Diamantes - Royalty'), ('03H', '03H - IPD - Produção de Ouro - Royalty'), ('04H', '04H - IPD - Produção de Outros Minerais - Royalty'), ('01J', '01J - IEC - Aeronaves e Embarcações de Recreio'), ('02J', '02J - IEC - Álcool e Outras Bebidas Alcoólicas'), ('03J', '03J - IEC - Armas de Fogo'), ('04J', '04J - IEC - Artefatos de Joalharia, Ourivesaria e Outros'), ('05J', '05J - IEC - Bebidas Açucaradas'), ('06J', '06J - IEC - Bebidas Energéticas'), ('07J', '07J - IEC - Cerveja'), ('08J', '08J - IEC - Fogo-de-artifício'), ('09J', '09J - IEC - Objetos de Arte, Coleção e Antiguidades'), ('10J', '10J - IEC - Produtos Derivados do Petróleo: Gasolina e Gasóleo'), ('11J', '11J - IEC - Tabaco e seus Derivados'), ('12J', '12J - IEC - Veículos Automóveis'), ('13J', '13J - IEC - Produtos Derivados do Petróleo: Gás Natural, Butano, Propano'), ('14J', '14J - IEC - Produtos Derivados do Petróleo - Outros'), ('01K', '01K - ICE - Exportação'), ('02K', '02K - ICE - Importação'), ('01L', '01L - IS - Contrato de Arrendamento'), ('02L', '02L - IS - Operações Bancárias'), ('03L', '03L - IS - Recibo de Quitação'), ('04L', '04L - IS - Operações Isentas (Regime Geral)'), ('05L', '05L - IS - Operações Isentas (Regime Simplificado)'), ('06L', '06L - IS - Outros'), ('01P', '01P - Multas Fiscais pela não Entrega da Declaração'), ('02P', '02P - Multas Fiscais pelo não Pagamento da Prestação da Dívida Tributária'), ('03P', '03P - Multa Substitutiva de Confisco Aduaneiro'), ('04P', '04P - Multas Fiscais'), ('05P', '05P - Multas Aduaneiras'), ('06P', '06P - Multas Institucionais'), ('07P', '07P - Adicional de 10% sobre as Multas Fiscais'), ('08P', '08P - Juros de Mora'), ('09P', '09P - Juros Compensatórios'), ('01Q', '01Q - Contribuições para o Fundo de Desenvolvimento Mineiro'), ('02Q', '02Q - Contribuições para Formação de Quadros Angolanos')], default=1, help_text='Código oficial da receita AGT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='data_declaracao',
            field=models.DateTimeField(blank=True, help_text='Data de envio da declaração à AGT', null=True),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='deducoes_permitidas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deduções permitidas pela legislação angolana', max_digits=12),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='numero_declaracao_agt',
            field=models.CharField(blank=True, help_text='Número da declaração na AGT', max_length=50),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='numero_guia_agt',
            field=models.CharField(blank=True, help_text='Número da guia de recolhimento AGT', max_length=50),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='total_agt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total a pagar à AGT em AOA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='configuracaoimposto',
            name='dia_vencimento_impostos',
            field=models.IntegerField(default=15, help_text='Dia do mês para vencimento dos impostos (padrão AGT: dia 15)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='configuracaoimposto',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_impostos_angola', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='configuracaoimposto',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações específicas sobre a configuração fiscal da empresa'),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='aliquota_percentual',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Alíquota em percentual (ex: 7.0000 para IVA 7%)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='metodo_calculo',
            field=models.CharField(choices=[('percentual_receita', 'Percentual sobre Receita'), ('percentual_lucro', 'Percentual sobre Lucro'), ('valor_fixo', 'Valor Fixo'), ('tabela_progressiva', 'Tabela Progressiva'), ('por_unidade', 'Por Unidade'), ('retencao_fonte', 'Retenção na Fonte'), ('outros', 'Outros')], default='percentual_receita', max_length=20),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='movimentacao_pagamento',
            field=models.ForeignKey(blank=True, help_text='Movimentação de pagamento do imposto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_angola_pagos', to='financeiro.movimentacaofinanceira'),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('eventual', 'Eventual')], default='mensal', max_length=15),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='regime_tributario',
            field=models.CharField(choices=[('geral', 'Regime Geral'), ('simplificado', 'Regime Simplificado'), ('iva_geral', 'Regime do IVA - Geral'), ('iva_simplificado', 'Regime do IVA - Simplificado'), ('iva_transitorio', 'Regime Transitório do IVA'), ('excluido_iva', 'Regime de Exclusão do IVA'), ('especial_petrolifero_mineiro', 'Regime Especial do Sector Petrolífero e Mineiro'), ('retencao_fonte', 'Regime de Retenção na Fonte'), ('isencao', 'Regime de Isenção')], help_text='Regime tributário aplicável', max_length=30),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Cálculo'), ('calculado', 'Calculado'), ('declarado', 'Declarado à AGT'), ('pago', 'Pago'), ('parcelado', 'Parcelado'), ('vencido', 'Vencido'), ('isento', 'Isento'), ('suspenso', 'Suspenso')], default='pendente', max_length=15),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor calculado do imposto em AOA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='valor_devido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor devido (após compensações) em AOA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='valor_fixo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo do imposto (se aplicável)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Juros por atraso em AOA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Multa por atraso em AOA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='impostotributo',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor efetivamente pago em AOA', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='impostotributo',
            unique_together={('empresa', 'codigo_receita_agt', 'ano_referencia', 'mes_referencia')},
        ),
        migrations.AddIndex(
            model_name='configuracaoimposto',
            index=models.Index(fields=['regime_tributario_principal'], name='financeiro__regime__e197b4_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaoimposto',
            index=models.Index(fields=['setor_atividade'], name='financeiro__setor_a_3e98ff_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaoimposto',
            index=models.Index(fields=['provincia'], name='financeiro__provinc_fe0abc_idx'),
        ),
        migrations.AddIndex(
            model_name='impostotributo',
            index=models.Index(fields=['codigo_receita_agt', 'situacao'], name='financeiro__codigo__bf3f16_idx'),
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='arquivo_guia',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='codigo_imposto',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='codigo_receita',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='deducoes',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='numero_darf',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='numero_referencia',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='tipo_imposto',
        ),
        migrations.RemoveField(
            model_name='impostotributo',
            name='total',
        ),
    ]
