# Generated by Django 5.1.5 on 2025-11-12 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_contas', to='core.empresa'),
        ),
    ]
