# Generated by Django 5.1.5 on 2025-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_configuracaoimposto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontas',
            name='codigo',
            field=models.CharField(help_text='Código da conta', max_length=20),
        ),
    ]
