# Generated by Django 5.1.5 on 2025-11-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_planocontas_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxocaixa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fluxocaixa',
            name='saldo_acumulado',
        ),
        migrations.RemoveField(
            model_name='fluxocaixa',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
