# Generated by Django 5.0.6 on 2025-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_movimentacaofinanceira_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
