# Generated by Django 5.0.6 on 2025-09-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamentofinanceiro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='tipo_dre',
            field=models.CharField(choices=[('receita', 'Receita Bruta'), ('deducao', 'Deduções/Impostos'), ('custo', 'Custo'), ('despesa', 'Despesa Operacional'), ('financeiro', 'Resultado Financeiro'), ('outros', 'Outros')], default='receita', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoriafinanceira'),
        ),
    ]
