# Generated by Django 5.0.6 on 2025-09-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_populate_tipo_dre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentocaixa',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('kwik', 'KWIK'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('vale', 'Vale'), ('outros', 'Outros')], default='dinheiro', max_length=20, verbose_name='Tipo'),
        ),
    ]
