# Generated by Django 5.0.6 on 2025-09-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminventario',
            options={'ordering': ['produto__nome_produto'], 'verbose_name': 'Item do Inventário', 'verbose_name_plural': 'Itens do Inventário'},
        ),
    ]
