# Generated by Django 5.0.6 on 2025-09-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome_comercial',
            new_name='nome_produto',
        ),
    ]
