# Generated by Django 5.0.6 on 2025-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_nome_comercial_produto_nome_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
