# Generated by Django 5.0.6 on 2025-09-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_data_validade_produto_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='lote',
        ),
    ]
