# Generated by Django 5.0.6 on 2025-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_maximo',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
