# Generated by Django 5.0.6 on 2025-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_estoque_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tem_iva',
            field=models.BooleanField(default=False, verbose_name='Tributado com IVA'),
        ),
    ]
