# Generated by Django 5.0.6 on 2025-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_tem_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tem_iva',
        ),
        migrations.AddField(
            model_name='produto',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
