# Generated by Django 5.0.6 on 2025-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produto_tem_iva_produto_iva_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_comercial',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
