# Generated by Django 5.0.6 on 2025-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produto_nome_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
