# Generated by Django 5.0.6 on 2025-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_desconto_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='produtos/fotos/produtos.png', null=True, upload_to='produtos/fotos/'),
        ),
    ]
