# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencaofonte',
            name='fornecedor',
            field=models.ForeignKey(help_text='Fornecedor/Prestador de serviço a quem foi efetuada a retenção', on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='assinaturadigital',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_fiscal', to='core.empresa'),
        ),
    ]
