# Generated by Django 4.2.10 on 2025-10-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('fiscal', '0003_documentofiscal_documentofiscallinha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='tipo_documento',
            field=models.CharField(choices=[('FT', 'Fatura Crédito'), ('REC', 'Recibo'), ('FR', 'Fatura-Recibo'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('VD', 'Venda a Dinheiro'), ('TV', 'Talão de Venda'), ('TD', 'Talão de Devolução'), ('AA', 'Alienação de Ativos'), ('DA', 'Devolução de Ativos'), ('RP', 'Prémio ou Penalização'), ('RE', 'Estorno ou Anulação'), ('CS', 'Imputação a Co-Produtos'), ('LD', 'Lançamentos Diversos'), ('RA', 'Resseguro Aceite'), ('RC', 'Resseguro Cedido')], max_length=3, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='SAFTExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo_tributacao', models.CharField(help_text='Formato YYYY-MM', max_length=7, verbose_name='Período de Tributação')),
                ('nome_arquivo', models.CharField(help_text='Ex: SAFT_2025-10_AOA.xml', max_length=255, verbose_name='Nome do Arquivo SAF-T')),
                ('caminho_arquivo', models.FileField(help_text='Arquivo XML gerado para envio AGT/SAF-T', upload_to='saft_exports/', verbose_name='Arquivo SAF-T')),
                ('hash_arquivo', models.CharField(blank=True, help_text='Garantia de integridade do arquivo SAF-T', max_length=256, verbose_name='Hash SHA-256 do arquivo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerado', 'Gerado'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='draft', max_length=20, verbose_name='Status do Export')),
                ('log_geracao', models.TextField(blank=True, help_text='Mensagens ou erros durante a geração do SAF-T', verbose_name='Log de Geração')),
                ('log_envio', models.TextField(blank=True, help_text='Mensagens ou erros durante o envio para AGT', verbose_name='Log de Envio')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saft_exports', to='core.empresa', verbose_name='Empresa')),
                ('usuario_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saft_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('usuario_geracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saft_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Exportação SAF-T',
                'verbose_name_plural': 'Exportações SAF-T',
                'ordering': ['-periodo_tributacao', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'periodo_tributacao'], name='fiscal_saft_empresa_f2adb8_idx'), models.Index(fields=['status'], name='fiscal_saft_status_f0f751_idx'), models.Index(fields=['hash_arquivo'], name='fiscal_saft_hash_ar_464d08_idx')],
            },
        ),
    ]
