# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('produtos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
    ]
