# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaftFiscalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Controlo Fiscal SAF-T',
                'verbose_name_plural': 'Controlo Fiscal SAF-T',
                'permissions': [('export_saft', 'Pode exportar o ficheiro SAF-T (Acesso a dados fiscais brutos)')],
                'managed': False,
            },
        ),
    ]
