# Generated by Django 5.0.6 on 2025-09-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_rename_pode_dispensar_controlados_cargo_pode_editar_produtos_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='funcionario',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo__nome__icontains': 'funcion'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(default='Serviço Padrão', max_length=100, unique=True),
        ),
    ]
