# Generated by Django 5.0.6 on 2025-09-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_initial'),
        ('core', '0001_initial'),
        ('funcionarios', '0002_rename_pode_dispensar_controlados_cargo_pode_editar_produtos_and_more'),
        ('servicos', '0002_alter_servico_funcionario_alter_servico_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentoservico',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço (Catálogo)', 'verbose_name_plural': 'Serviços (Catálogo)'},
        ),
        migrations.RemoveIndex(
            model_name='agendamentoservico',
            name='servicos_ag_data_ho_96cca4_idx',
        ),
        migrations.RemoveIndex(
            model_name='agendamentoservico',
            name='servicos_ag_status_3c6425_idx',
        ),
        migrations.RemoveIndex(
            model_name='servico',
            name='servicos_se_numero__d1ae48_idx',
        ),
        migrations.RemoveIndex(
            model_name='servico',
            name='servicos_se_nome_11df0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='servico',
            name='servicos_se_cliente_70659a_idx',
        ),
        migrations.RemoveIndex(
            model_name='servico',
            name='servicos_se_funcion_ded61e_idx',
        ),
        migrations.RenameField(
            model_name='agendamentoservico',
            old_name='motivo_cancelamento',
            new_name='resultado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='duracao_minutos',
            new_name='duracao_padrao_minutos',
        ),
        migrations.RemoveField(
            model_name='agendamentoservico',
            name='duracao_minutos',
        ),
        migrations.RemoveField(
            model_name='agendamentoservico',
            name='nome_completo',
        ),
        migrations.AlterUniqueTogether(
            name='servico',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AddField(
            model_name='agendamentoservico',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentoservico',
            name='data_fim_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamentoservico',
            name='data_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamentoservico',
            name='valor_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='instrucoes_padrao',
            field=models.TextField(blank=True, help_text='Instruções para o cliente ou para o funcionário.'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco_padrao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentoservico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_servicos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='agendamentoservico',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='agendamentoservico',
            name='servico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='servicos.servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentoservico',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('faltou', 'Cliente Faltou')], default='agendado', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='template_email_mensagem',
            field=models.TextField(default='Olá {nome_paciente},\n\n\n\nEste é um lembrete de que você tem uma consulta agendada:\n\n📅 Data: {data_consulta}\n🕐 Horário: {hora_consulta}\n👨\u200d⚕️ Profissional: {farmaceutico}\n🏥 Tipo de Serviço: {servico}\n\nPor favor, chegue com 15 minutos de antecedência.\n\nAtenciosamente,\n{nome_empresa}'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_catalogo', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='servico',
            name='avaliacao_cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='comentario_cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data_realizacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='numero_servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='observacoes_agendamento',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='observacoes_realizacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='preco_servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='recomendacoes',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='resultado_servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='status',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='usuario_criacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_final',
        ),
    ]
