# Generated by Django 5.0.6 on 2025-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_agendamentoservico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, default='servicos/fotos/servico.png', null=True, upload_to='servicos/fotos/'),
        ),
    ]
