# Generated by Django 5.0.6 on 2025-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto promocional em % (ex: 10 = 10%)', max_digits=5),
        ),
    ]
