# Generated by Django 5.0.6 on 2025-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servico_desconto_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='iva_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
