# Generated by Django 5.0.6 on 2025-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_servico_iva_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao_servico_padrao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='instrucoes_servico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
