# Generated by Django 5.0.6 on 2025-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'ordering': ['produto'], 'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('laboratorio', 'Laboratório Farmacêutico'), ('distribuidor', 'Distribuidor'), ('atacadista', 'Atacadista'), ('importador', 'Importador'), ('representante', 'Representante'), ('cooperativa', 'Cooperativa'), ('prestador_servico', 'Prestador de Serviço'), ('outros', 'Outros')], default='distribuidor', max_length=20),
        ),
    ]
