# Generated by Django 5.0.6 on 2025-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_itempedido_options_alter_fornecedor_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='foto',
            field=models.ImageField(blank=True, default='fornecedores/fotos/fornecedor.png', null=True, upload_to='fornecedores/fotos/'),
        ),
    ]
