# Generated by Django 5.0.6 on 2025-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_fornecedor_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratofornecedor',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='cotacaofornecedor',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='valor_total',
            new_name='total',
        ),
    ]
