# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecomanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='produtocomanda',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.categoriacomanda'),
        ),
        migrations.AddField(
            model_name='produtocomanda',
            name='centro_requisicao',
            field=models.ForeignKey(blank=True, help_text='Centro responsável pelo preparo deste item', null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.centrorequisicao'),
        ),
        migrations.AddField(
            model_name='produtocomanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='item_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.itemcomanda'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='pagamento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.pagamento'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
        ),
        migrations.AddField(
            model_name='itemtemplatecomanda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandas.produtocomanda'),
        ),
        migrations.AddField(
            model_name='itemtemplatecomanda',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_template', to='comandas.templatecomanda'),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.produtocomanda'),
        ),
        migrations.AddField(
            model_name='historicocomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='historicocomanda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracaocomanda',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_comandas', to='core.empresa'),
        ),
    ]
