# Generated by Django 4.2.10 on 2025-10-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0002_initial'),
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('clientes', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas_atendidas', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.mesa'),
        ),
        migrations.AddField(
            model_name='centrorequisicao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='centrorequisicao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_responsavel', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='categoriacomanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddIndex(
            model_name='produtocomanda',
            index=models.Index(fields=['codigo'], name='comandas_pr_codigo_84ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='produtocomanda',
            index=models.Index(fields=['categoria', 'disponivel'], name='comandas_pr_categor_de5500_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocomanda',
            index=models.Index(fields=['comanda', 'data_movimentacao'], name='comandas_mo_comanda_34d380_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocomanda',
            index=models.Index(fields=['tipo_movimentacao', 'data_movimentacao'], name='comandas_mo_tipo_mo_c15bf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'loja')},
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['numero_comanda'], name='comandas_co_numero__c5502c_idx'),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['status', 'data_abertura'], name='comandas_co_status_eb44c5_idx'),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['atendente', 'data_abertura'], name='comandas_co_atenden_66e14d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='centrorequisicao',
            unique_together={('codigo', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriacomanda',
            unique_together={('nome', 'empresa')},
        ),
    ]
