# Generated by Django 5.0.6 on 2025-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='itemcomanda',
            old_name='valor_total',
            new_name='total',
        ),
    ]
