# Generated by Django 5.1.5 on 2025-11-11 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('vendas_baixas', 'Vendas Baixas'), ('erro_sistema', 'Erro do Sistema'), ('performance', 'Performance'), ('seguranca', 'Segurança'), ('financeiro', 'Financeiro')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='ativo', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('dados_contexto', models.JSONField(default=dict)),
                ('acoes_sugeridas', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.empresa')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta Inteligente',
                'verbose_name_plural': 'Alertas Inteligentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_operacao', models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Exclusão')], max_length=10)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_posteriores', models.JSONField(blank=True, null=True)),
                ('campos_alterados', models.JSONField(default=list)),
                ('motivo', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict)),
                ('widgets', models.JSONField(default=list)),
                ('filtros_padrao', models.JSONField(default=dict)),
                ('padrao', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Personalizado',
                'verbose_name_plural': 'Dashboards Personalizados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('navegacao', 'Navegação'), ('vendas', 'Vendas'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('usuario', 'Usuário'), ('sistema', 'Sistema'), ('erro', 'Erro')], max_length=20)),
                ('acao', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('propriedades', models.JSONField(default=dict)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_analytics', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Analytics',
                'verbose_name_plural': 'Eventos Analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada', models.BooleanField(default=False)),
                ('lida', models.BooleanField(default=False)),
                ('via_email', models.BooleanField(default=True)),
                ('via_sistema', models.BooleanField(default=True)),
                ('via_whatsapp', models.BooleanField(default=False)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.alertainteligente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('alerta', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='alertainteligente',
            name='usuarios_notificados',
            field=models.ManyToManyField(related_name='alertas_recebidos', through='analytics.NotificacaoAlerta', to=settings.AUTH_USER_MODEL),
        ),
    ]
